config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
      resources :users
  end
  resources :users, only: [:new, :create, :show, :destroy]
  resources :tasks
  root 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :status, presence: true
  validates :importance, presence: true
  scope :desc_created, -> {order(created_at: :desc)}
  scope :asc_end_on, -> {order(end_on: :asc)}
  scope :desc_importance, -> {order(importance: :desc)}
  scope :where_like_status, -> (status) {where(['status LIKE ?', "#{status}"])}
  scope :where_like_title, -> (title) {where(['title LIKE ?', "%#{title}%"])}
  scope :label_name_search, -> (label_search) {Task.joins(:labels).where(['labels.title LIKE ?', "%#{label_search}%"])}
  #scope :where_like_label, -> (title) {labels.where(['label LIKE ?', "#{title}"])}
  scope :where_like_status_title, -> (title, status) {where(['title LIKE ? AND status LIKE ?', "%#{title}%", "#{status}"])}
  enum importance: {低: 0,中: 1,高: 2,}
  belongs_to :user, optional: true
  has_many :task_labels, dependent: :destroy, foreign_key: 'task_id'
  has_many :labels, through: :task_labels, source: :label
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    if logged_in?
      @tasks = Task.all.page(params[:page]).per(6)
      if params[:sort_expired]
        @tasks = Task.all.page(params[:page]).per(6).asc_end_on
      elsif params[:sort_importance]
        @tasks = Task.all.page(params[:page]).per(6).desc_importance
      elsif params[:search] && params[:title].blank? && params[:status].blank? && params[:label_search].blank?
        puts "3つとも空だよ"
      elsif params[:search] && params[:title].blank? && params[:status].blank?
        puts "label検索だよ"
        @tasks = Task.page(params[:page]).per(6).label_name_search(params[:label_search])
      elsif params[:search] && params[:title].blank?
        puts "状態検索だよ"
        @tasks = Task.page(params[:page]).per(6).where_like_status(params[:status])
      elsif params[:search] && params[:status].blank?
         puts "タイトル検索だよ"
        @tasks = Task.page(params[:page]).per(6).where_like_title(params[:title])
      elsif params[:search]
         puts "タイトルと状態で検索だよ"
        @tasks = Task.page(params[:page]).per(6).where_like_status_title(params[:title],params[:status])
      else
        @tasks = Task.all.page(params[:page]).per(6).desc_created
      end
    else
      redirect_to new_session_path , notice: 'loginしてください。'
    end

  end

  # GET /tasks/
  def show
    #user_id = Task.find(params[:id]).user.id
    if logged_in?
        @task = Task.find(params[:id])
    else
        redirect_to :back , notice: 'loginしてください。'
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    if logged_in?
        @task = Task.find(params[:id])
    else
        redirect_to new_session_path , notice: 'loginしてください。'
    end
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:title, :content, :end_on, :status, :search, :importance, label_ids: [])
    end

    def correct_user
      @task = Task.find(params[:id])
      if current_user.id != @task.user.id
        redirect_to new_session_path , notice: 'loginしてください。'
      end
    end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :end_on %>
    <%= form.date_field :end_on %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ["未着手","着手","完了"], {include_blank: '未設定'} %>
  </div>

  <div class="field">
    <%= form.label :importance %>
    <%= form.select :importance, ["高","中","低"], {include_blank: '未設定'} %>
  </div>

  <div class="field">
  <% Label.all.each do |label| %>
      <% if action_name == 'new' || action_name == 'create' %>
        <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id], "" %>
        <%= label.title %>
      <% elsif action_name == 'edit' || action_name == 'update' %>
        <%= form.check_box :label_ids, { multiple: true, checked: @task.label_ids.include?(label.id), disabled: label[:disabled], include_hidden: false}, label[:id], "" %>
        <%= label.title %>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= form_with(method: :get, url: tasks_path, local: true) do |form| %>
  <div style="display:inline-flex">
    <%= form.label :title_search, "タイトル検索" %>
    <%= form.text_field :title %>
    <%= form.label :status_search, "状態検索" %>
    <%= form.select :status, ["未着手","着手","完了"], include_blank: "タスクの状態" %>
    <%= form.label :label_name, 'ラベル検索' %>
    <%= form.search_field :label_search %>
　　 <%= form.hidden_field :search, value: 'true' %>
    <%= form.submit "検索"%>
  </div>
<% end %>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Deadline</th>
      <th>State</th>
      <th>Importance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <% if current_user.id == task.user.id %>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.end_on %></td>
        <td><%= task.status %></td>
        <td><%= task.importance %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>

  </tbody>
</table>
</div>
<br>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %>
<br>
<%= link_to "重要度でソートする", tasks_path(sort_importance: "true") %>
<br>
<%= link_to 'taskを新規作成する', new_task_path %>
<br>
<%= link_to 'user管理ページに遷移する', admin_users_path %>
<br>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p>詳細ページ</p>

<p>
  <strong>title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.end_on %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Importance:</strong>
  <%= @task.importance %>
</p>

<p>
  <strong>Label:</strong>
<% @task.labels.each do |task_label| %>
  <%= task_label.title %>
<% end %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>