config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
      resources :users
  end
  resources :users, only: [:new, :create, :show, :destroy]
  resources :tasks
  root 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  #before_update :admin_user_present
  #before_destroy :admin_user_present
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :tasks, dependent: :destroy
   #def admin_user_present
    # raise ActiveRecord::Rollback if User.where(admin: true).count == 1
   #end
   before_destroy do
     throw(:abort) if User.where(admin: true).count <= 1 && self.admin?
   end

   before_update do
    throw(:abort) if User.where(admin: true).count <= 1 && self.admin?
   end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:index, :show, :new, :destroy, :update]
  # GET /users
  def index
    @users = User.all.page(params[:page]).per(30)
  end

  # GET /users/1
  def show


  end

  # GET /users/new
  def new
    @user = User.new

  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      render :new
    end
    #log_in @user
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      render :edit, notice: '管理者ユーザー数は0にはできません'
    end
  end

  # DELETE /users/1
  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'User was successfully destroyed.'
    else
      redirect_to admin_users_path, notice: '管理者ユーザー数は0にはできません'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end

    def admin_user
      redirect_to tasks_path, notice: '管理者権限がありません' unless current_user.admin

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    if current_user.id != @user.id
      redirect_to tasks_path, notice: '他ユーザーは閲覧できません'
    end
  end

  # GET /users/new
  def new
    if logged_in?
      redirect_to tasks_path, notice: 'login中です'
    else
      @user = User.new
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      #log_in @user
      #binding.pry
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
    #log_in @user
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h1>Sign up</h1>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
  <br>
  <%= form.submit "Create my account" %>

<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Taskを作成する', new_task_path %>