config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
      resources :users
  end
  resources :users, only: [:new, :create, :show, :destroy]
  resources :tasks
  root 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  #before_update :admin_user_present
  #before_destroy :admin_user_present
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :tasks, dependent: :destroy
   #def admin_user_present
    # raise ActiveRecord::Rollback if User.where(admin: true).count == 1
   #end
   before_destroy do
     throw(:abort) if User.where(admin: true).count <= 1 && self.admin?
   end

   before_update do
    throw(:abort) if User.where(admin: true).count <= 1 && self.admin?
   end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:index, :show, :new, :destroy, :update]
  # GET /users
  def index
    @users = User.all.page(params[:page]).per(30)
  end

  # GET /users/1
  def show


  end

  # GET /users/new
  def new
    @user = User.new

  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      render :new
    end
    #log_in @user
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      render :edit, notice: '管理者ユーザー数は0にはできません'
    end
  end

  # DELETE /users/1
  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'User was successfully destroyed.'
    else
      redirect_to admin_users_path, notice: '管理者ユーザー数は0にはできません'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end

    def admin_user
      redirect_to tasks_path, notice: '管理者権限がありません' unless current_user.admin

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    if current_user.id != @user.id
      redirect_to tasks_path, notice: '他ユーザーは閲覧できません'
    end
  end

  # GET /users/new
  def new
    if logged_in?
      redirect_to tasks_path, notice: 'login中です'
    else
      @user = User.new
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      #log_in @user
      #binding.pry
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
    #log_in @user
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin,@user], local: true do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.label :admin %>
  <%= form.select :admin, [["無効", false], ["有効", true]] %>
  <br>
  <%= form.submit "Create User" %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>
<%= form_with model: [:admin,@user], local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>


  <%= form.label :admin %>
  <%= form.select :admin, [["無効", false], ["有効", true]] %>
  <br>
  <%= form.submit "Create User" %>
<% end %>

<%= link_to 'Show', @user %>
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th>Tasks_counts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>

        <td><%= link_to user.name, admin_user_path(user)%></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <th><%= user.tasks.count %></th>

      </tr>
    <% end %>

  </tbody>
</table>
</div>

<br>
<%= link_to 'userを新規作成する', new_admin_user_path %>
<br>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<br>
<br>
<br>
<br>
<br>
<h1>Create user</h1>

<%= form_with model: [:admin,@user], local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.label :admin %>
  <%= form.select :admin, [["無効", false], ["有効", true]] %>
  <br>
  <%= form.submit "Create User" %>
<% end %>



<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p>
  <strong>
      <%= @user.name + "のページ" %>
  </strong>
</p>

<div>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Deadline</th>
      <th>State</th>
      <th>Importance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.end_on %></td>
        <td><%= task.status %></td>
        <td><%= task.importance %></td>

      </tr>
    <% end %>

  </tbody>
</table>
</div>


<%= link_to 'userを編集する',edit_admin_user_path(@user) %>
<br>
<%= link_to 'userを削除する',admin_user_path(@user), method: :delete%>
<br>
<%= link_to 'userを作成する', new_admin_user_path %>